### ISSUE TITLE
ShinyProxy 2.4.0 on K8S throws errors

### ISSUE THREAD

**Issue by remche** [openanalytics/shinyproxy#239]
After updating to 2.4.0, Shinyproxy log shows a lot of error like the following :
```
2020-10-15 15:21:19.686 ERROR 1 --- [   XNIO-1 I/O-1] org.xnio.listener                        : XNIO001007: A channel event listener threw an exception

java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at eu.openanalytics.containerproxy.util.DelegatingStreamSourceConduit.read(DelegatingStreamSourceConduit.java:117) ~[containerproxy-0.8.5.jar!/:0.8.5]
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127) ~[xnio-api-3.8.0.Final.jar!/:3.8.0.Final]
	at io.undertow.util.Transfer$TransferListener.handleEvent(Transfer.java:212) ~[undertow-core-2.1.3.Final.jar!/:2.1.3.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.0.Final.jar!/:3.8.0.Final]
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) [xnio-api-3.8.0.Final.jar!/:3.8.0.Final]
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89) [xnio-nio-3.8.0.Final.jar!/:3.8.0.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591) [xnio-nio-3.8.0.Final.jar!/:3.8.0.Final]
```

**Comment by LEDfan** [comment]
Hi @remche 

We are aware of this error. This error happens when you try to run ShinyProxy 2.4.0 using JDK 8. We changed some pieces in our build infrastructure, since then our JARs are build using OpenJDK 11, therefore they don't run on JDK 8.

A simple solution for you should be to change you Docker container to use OpenJDK11.

However, we plan to build again using OpenJDK 8 for the 2.4.1 release (which we should release soon).

**Comment by remche** [comment]
Oh I see, thanks for the follow-up. 
Will next versions stick only on JDK8 or do you plan to use both JDK8 and JDK11 ?

**Comment by LEDfan** [comment]
We will compile using JDK8 and those version should work on any JDK >= 8. Our official images use OpenJDK 11 and we plan to keep doing so, in order to take advantage of the latest changes to the JDK.

**Comment by LEDfan** [comment]
We just released [https://shinyproxy.io/downloads/#241](ShinyProxy 2.4.1) which is now again built using JDK 8.
I close this issue now, but don't hesitate to open a new issue if you encounter a new issue!
